language: python
cache: pip

python:
  - "2.7"
  - "3.6"
  - "3.7"

sudo: false

env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<2.0"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django==2.2.12"
  - DJANGO="Django==3.1.6"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"

matrix:
  fast_finish: true
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "2.7"
      env: DJANGO="Django==2.2.12"
    - python: "2.7"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.4"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.6"
      env: DJANGO="Django>=1.8,<1.11"
    - python: "2.7"
      env: DJANGO="Django==3.1.6"

  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

install:
  - pip install coveralls coverage
  - pip install $DJANGO

script:
  - coverage run runtests.py
  - coverage report -m

after_script:
  - coverage combine
  - coveralls
